version: '3.8'

services:
  postgres:
    container_name: streamy_db
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_DB_USER}
      POSTGRES_PASSWORD: ${PSQL_DB_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}    
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256  
    volumes:
      - postgresdata:/data/postgres
    ports:
      - '${DB_PORT}:5432'

volumes:
  postgresdata:
    driver: local
